### PR TITLE
feat: add disk space to hosts tab in phenix ui

### PR DESCRIPTION
**Pull request by glattercj**
Add disk space % to Hosts tab in phenix UI - uses `df` on `common.PhenixBase` and `common.MinimegaBase`.

Screenshot 2024-02-08 at 21 46 00

### CODE REVIEW

**Comment by activeshadow** [comment]
@glattercj can you revert all of the `this --> m` changes that you made in this PR please?

**Comment by activeshadow** [comment]
> > @glattercj can you revert all of the `this --> m` changes that you made in this PR please?
> 
> Sure. I thought it was more ideomatic to not use the `this` keyword in Golang.


@glattercj it is... but I use `this` exclusively within the phēnix code base. It's pretty much the only idiomatic rule I don't follow. :joy:

**Comment by glattercj** [comment]
> > > @glattercj can you revert all of the `this --> m` changes that you made in this PR please?
> > 
> > 
> > Sure. I thought it was more ideomatic to not use the `this` keyword in Golang.
> 
> @glattercj it is... but I use `this` exclusively within the phēnix code base. It's pretty much the only idiomatic rule I don't follow. 😂

Done...smh

**Comment by glattercj** [comment]
@activeshadow Tested with single and multi-node - g2g.

**Pull request merged**
