### PR TITLE
image create: add flag to skip default packages

### PR DESCRIPTION
**Pull request by jacdavi**
cc @aherna

### CODE REVIEW

**Comment by activeshadow** [comment]
LGTM

@jacdavi Looks simple enough. I assume you tested already? Do you want me to wait to merge?

**Comment by jacdavi** [comment]
Arthur was going to test it out since it was something he needed. He hasn't tried it yet, so we can wait a little bit.

**Comment by activeshadow** [comment]
@aherna have you had a chance to look at this yet?

**Comment by activeshadow** [comment]
@jacdavi @aherna any updates on testing this?

**Comment by jacdavi** [comment]
@activeshadow sorry for the really long delay. Just double checked and it works as expected. The created config excludes default packages.

**Pull request merged**
